nobl9/terraform-provider-nobl9

README.md, docs/index.md
- Updates code to match public release source instead of self-hosted path
- bumps to the latest version
=> Updates terraform code example to public source

codefresh.yml, nobl9/resource_agent_test.go, nobl9/resource_alert_policy_test.go, nobl9/resource_role_binding_test.go, nobl9/resource_slo_test.go
Adds the provider to CodeFresh CI and runs the tests
- Adding debugging options
- Adding Suppress Diff function for alert methods
- Changing test to be parallel
- Adding comment
- Adding codefresh config and test fixes
- Adding more alert policy tests
=> SRE-742 Add provider to CodeFresh

nobl9/resource_slo.go, nobl9/resource_slo_test.go
AlertPolicy in SLO is returned in nondeterministic order from N9 API. This change ignores the order of element in alert policy list using `DiffSuppressFunc`
test before:
```
=== RUN   TestAcc_Nobl9SLO/test-multiple-ap
resource_slo_test.go:42: Step 1/1 error: After applying this test step, the plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "nobl9_slo" "test-multiple-ap" {
~ alert_policies   = [
- "test-multiple-ap-fast",
"test-multiple-ap-slow",
+ "test-multiple-ap-fast",
]
id               = "test-multiple-ap"
name             = "test-multiple-ap"
+ objective {
+ display_name      = "obj1"
+ op …
```
=> PC-4879 Ignore AlertPolicy order in SLO

.golangci.yml, codefresh.yml, main.go, nobl9/doc.go, nobl9/metadata_schema.go, nobl9/metric_spec.go, nobl9/provider.go, nobl9/provider_test.go, nobl9/resource_agent.go, nobl9/resource_agent_test.go, nobl9/resource_alert_policy.go, nobl9/resource_alertmethod.go, nobl9/resource_role_binding.go, nobl9/resource_role_binding_test.go, nobl9/resource_service.go, nobl9/resource_service_test.go, nobl9/resource_slo.go, nobl9/resource_slo_test.go
* Added checks for Go files
* Temporary suppressed linter issues
* Fixes and improvements for pipeline
* Slack notification about pipeline failure
=> PC-5265 Trigger terraform tests and go files checks

codefresh.yml
Slack notification about pipeline failure only for changes to `main` branch
=> PC-5265 Notify only for failures in main branch

examples/resources/nobl9_alert_policy/resource.tf, examples/resources/nobl9_project/resource.tf, examples/resources/nobl9_service/resource.tf, nobl9/resource_agent_test.go, nobl9/resource_slo_test.go
- bring back creating agents in `TestAcc_Nobl9SLO` 
- unskip tests `TestAcc_Nobl9Agent`
=> Pc 5701 create a new configuration for tests and restore Agents creation via API 

nobl9/resource_slo.go
When deleting the whole `alert_policies` list from **SLO** resource, the change is not noticed and therefore, alert policies are not deleted from the resource.
The internal Terraform **GetChange** function fails to notice a change when a resource is reapplied after unsetting an optional list resource. According to the documentation:
> // HasChange should be used to check if a change exists. It is possible
// that both the old and new value are the same if the old value was not
// set and the new value is. This is common, for example, for boolean
// fields which have a zero value of false.
This PR introduces a fix to the logic of checking the diff on alert policies, that forces to check the difference in size of arrays. Values for this check are gathered from **DiffSuppressFunc,** and not …
=> Fix deleting alert policies from SLOs

docs/resources/slo.md, examples/resources/nobl9_slo/resource.tf, go.mod, go.sum, nobl9/resource_slo.go, nobl9/resource_slo_test.go
This PR includes changes to Nobl9's terraform provider. It adds objective name field to SLO resource.
=> PC-5799 Add terraform provider support for objective name in kind SLO

docs/resources/project.md, nobl9/resource_project.go, templates/resources/project.md.tmpl
This PR amends incorrect links to our product documentation.
=> PM-970 correct link to YAML guide

docs/resources/alert_method_jira.md, docs/resources/alert_method_msteams.md, docs/resources/alert_method_opsgenie.md, docs/resources/alert_method_pagerduty.md, docs/resources/alert_method_servicenow.md, docs/resources/alert_method_slack.md, examples/resources/nobl9_alert_method_jira/resource.tf, examples/resources/nobl9_alert_method_msteams/resource.tf, examples/resources/nobl9_alert_method_opsgenie/resource.tf, examples/resources/nobl9_alert_method_pagerduty/resource.tf, examples/resources/nobl9_alert_method_servicenow/resource.tf, examples/resources/nobl9_alert_method_slack/resource.tf
This PR corrects our sample resource configs for our Terraform registry documentation.
=> Correct alert method samples

docs/resources/direct_dynatrace.md, examples/resources/nobl9_direct_dynatrace/resource.tf, nobl9/resource_direct.go, nobl9/resource_direct_test.go
Reverts nobl9/terraform-provider-nobl9#88
=> Revert "Enable Dynatrace QueryEngine"

README.md, examples/provider/provider.tf, examples/resources/nobl9_slo/resource.tf, nobl9/resource_alertmethod_mock.go
This PR adds examples for anomaly_config in SLO Spec and fixes a [linter issue](https://g.codefresh.io/build/6458e5179a63e6354dff1832?step=lint&tab=output&logs=terminal) introduced in `v0.11.0`
=> Update examples with anomaly_config

nobl9/resource_direct.go, nobl9/resource_direct_test.go
- appdynamics
- dynatrace
- influxdb
- instana
- splunk
- sumologic
- newrelic
=> PC-9151 Enable Log Collection for other directs

Makefile, main.go, nobl9/anomaly_config_schema_test.go, nobl9/metadata_schema.go, nobl9/provider.go, nobl9/resource_agent.go, nobl9/resource_alertmethod.go, nobl9/resource_slo.go, nobl9/resource_slo_test.go
A few tweaks enabling a `golangci-lint` update.
=> fix: linter fixes

nobl9/resource_agent.go, nobl9/resource_direct.go
=> PC-10671 Fix lint issue

README.md, dev-docs/DEVELOPMENT.md
Added Nobl9 logo and improved README.md.
=> chore: Add logo and improve README

README.md
Correct the colour scheme selection references.
=> chore: Fix README.md logo

.github/pull_request_template.md, .github/release-drafter.yml, .github/scripts/release-notes.sh, .markdownlint.yaml, Makefile, README.md, dev-docs/DEVELOPMENT.md
Introduce changes to Release Drafter previously tested in sloctl and nobl9-go.
Ref: https://github.com/nobl9/sloctl/commit/df14048a1ce4289d22ec1cbcd86980913535040a
=> chore: Update Release Drafter

.github/workflows/release.yml
This PR updates the yaml so it uses the newly added keys
=> chore: Update keys in release.yml

.github/workflows/release.yml
Management approval will take place in the Nobl9 internal tool.
=> chore: Remove management approval release step

nobl9/resource_budgetadjustment_test.go
=> fix: PC-11815 terraform tests fix

docs/resources/slo.md, examples/resources/nobl9_slo/resource.tf
Repo was lacking composite SLO example.
Added missing example.
=> feat: PC-12978 Add composite examples

.github/workflows/acc-tests-dispatch.yml
Use _vars.TERRAFORM_NOBL9_PROJECT_ for the default dispatch project.
=> chore: Update acc-tests-dispatch.yml

dev-docs/DEVELOPMENT.md
Update make command for building Terraform Provider locally.
=> chore: Fix local provider installation guide

.github/release-drafter.yml, .github/renovate.json5, .github/scripts/release-notes.sh, .golangci.yml
Synced the following files:
- .golangci.yml
- .github/renovate.json5
- .github/release-drafter.yml
- .github/scripts/release-notes.sh
Root repository ref: https://github.com/nobl9/go-repo-template
Pull request generated by [gitsync](https://github.com/nieomylnieja/gitsync)
=> chore: gitsync updates

docs/resources/slo.md, examples/resources/nobl9_slo/resource.tf, nobl9/resource_slo.go, nobl9/resource_slo_composite.go, templates/resources/slo.md.tmpl
It wasn't clear whether composite example in the documentation is for legacy ones or composites 2.0.
Added clarifying comments to the documentation.
=> chore: PC-13787 Distinguish composite 2.0 example

Makefile, README.md, dev-docs/RELEASE.md
Bumping the version before a release.
=> chore: PC-13787 Bump version

nobl9/resource_direct_test.go
Skipping the test until tomorrow's fix.
=> chore: Skip GCM direct test

docs/resources/agent.md, docs/resources/direct_datadog.md, nobl9/resource_agent.go, nobl9/resource_direct.go
Update documentation to be consistent with docs.nobl9.com
Updated Datadog site list.
No testing needed
=> chore: Update datadog site list

docs/resources/direct_datadog.md, examples/resources/nobl9_direct_datadog/resource.tf, nobl9/resource_agent_test.go, nobl9/resource_direct_test.go
Update datadog site to use new values
=> chore: Update datadog site in examples and tests

nobl9/provider_test.go
Enhancing error message to facilitate debugging.
=> chore: Enhance error message

nobl9/resource_slo.go
This reverts commit d44dd844f0895f360ab3f338ed284f066a1060be.
=> fix: Revert "fix: Set ForceNew to true for service in SLO (#345)"

.golangci.yml, docs/resources/agent.md, docs/resources/direct_appdynamics.md, docs/resources/direct_azure_monitor.md, docs/resources/direct_cloudwatch.md, docs/resources/direct_datadog.md, docs/resources/direct_dynatrace.md, docs/resources/direct_gcm.md, docs/resources/direct_honeycomb.md, docs/resources/direct_lightstep.md, docs/resources/direct_logic_monitor.md, docs/resources/direct_newrelic.md, docs/resources/direct_splunk.md, examples/resources/nobl9_direct_appdynamics/resource.tf, examples/resources/nobl9_direct_azure_monitor/resource.tf, examples/resources/nobl9_direct_cloudwatch/resource.tf, examples/resources/nobl9_direct_datadog/resource.tf, examples/resources/nobl9_direct_dynatrace/resource.tf, examples/resources/nobl9_direct_honeycomb/resource.tf, examples/resources/nobl9_direct_lightstep/resource.tf, examples/resources/nobl9_direct_logic_monitor/resource.tf, examples/resources/nobl9_direct_newrelic/resource.tf, examples/resources/nobl9_direct_splunk/resource.tf, go.mod, nobl9/anomaly_config_schema_test.go, nobl9/historical_data_retrieval_schema.go, nobl9/resource_agent_test.go, nobl9/resource_direct_test.go, nobl9/resource_report_test.go
The feature will be reworked. Meanwhile we remove the fields to avoid confusionn.
Remove `triggered_by_slo_creation` and `triggered_by_slo_edit` fields that currently have no effect.
=> chore: PC-15033 Remove experimental fields

docs/resources/budget_adjustment.md, templates/resources/budget_adjustment.md.tmpl
This PR updates the outdated description of managing adjustments via Nobl9 Terraform provider.
=> chore: Update adjustments description

nobl9/resource_slo_test.go
Fix failing test because of wrong formatting multiline string [
=> chore: Fix failing test because of wrong formatting multiline string [PC-13052]

nobl9/resource_alertmethod_test.go
Fix broken acceptance tests.
**Before:**
> --- FAIL: TestAcc_Nobl9AlertMethod (0.00s)
--- PASS: TestAcc_Nobl9AlertMethod/test-webhook (3.21s)
--- PASS: TestAcc_Nobl9AlertMethod/test-opsgenie (3.25s)
--- FAIL: TestAcc_Nobl9AlertMethod/test-email-plain-text (2.51s)
--- FAIL: TestAcc_Nobl9AlertMethod/test-email-plain (2.54s)
--- PASS: TestAcc_Nobl9AlertMethod/test-email (3.11s)
--- PASS: TestAcc_Nobl9AlertMethod/test-teams (3.17s)
--- PASS: TestAcc_Nobl9AlertMethod/test-jira (3.09s)
--- PASS: TestAcc_Nobl9AlertMethod/test-servicenow (3.18s)
--- PASS: TestAcc_Nobl9AlertMethod/test-pagerduty-send-resolution (3.19s)
--- PASS: TestAcc_Nobl9AlertMethod/test-discord (3.11s)
--- PASS: TestAcc_Nobl9AlertMethod/test-slack (3.15s)
--- PASS: TestAcc_Nobl9AlertMethod/test-pagerduty-send-resolution-messag …
=> fix: Fix acceptance tests of Email AlertMethod
