README.md
nobl9/resource_alert_policy_test.go
nobl9/resource_slo.go
nobl9/resource_slo_test.go

N9 API returns `attachments[].displayName` but terraform provider expects `attachments[].display_name`.
This resulted in error `panic: Invalid address to set: []string{"attachments", "0", "displayName"}` when trying to use attachments.
Change was tested against `main` environment:
```
go test ./... -test.run=TestAcc_Nobl9SL
O/test-prom -v -timeout 5m
?   	github.com/nobl9/terraform-provider-nobl9	[no test files]
=== RUN   TestAcc_Nobl9SLO
=== PAUSE TestAcc_Nobl9SLO
=== CONT  TestAcc_Nobl9SLO
=== RUN   TestAcc_Nobl9SLO/test-prometheus
=== RUN   TestAcc_Nobl9SLO/test-prom-with-ap
=== RUN   TestAcc_Nobl9SLO/test-prom-with-countmetrics
=== RUN   TestAcc_Nobl9SLO/test-prom-with-multiple-objectives
=== RUN   TestAcc_Nobl9SLO/test-prom-full
=== RUN   TestAcc_Nobl9SLO/test-prom-with-time-slices …
```

fix: Accept attachments in SLO resource

---

Makefile
docs/index.md
go.mod
nobl9/resource_slo.go

FIxing typo that would cause `index out of range [0] with length 0`.

Fix typo in resource_slo.go

---

.github/workflows/goreleaser.yml
Makefile
README.md
docs/index.md

hashicorp/ghaction-import-gpg@v2.1.0 is now deprecated - we should use crazy-max/ghaction-import-gpg@v5
The issue was spotted during a tag realease - https://github.com/nobl9/terraform-provider-nobl9/runs/7632746572?check_suite_focus=true#step:5:4
I have tested with first:
```
name: release
on:
push: {}
jobs:
goreleaser:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v2.4.0
- name: Unshallow
run: git fetch --prune --unshallow
- name: Set up Go
uses: actions/setup-go@v2
with:
go-version: 1.17
- name: Import GPG key
id: import_gpg
uses: hashicorp/ghaction-import-gpg@v2.1.0
env:
GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
PASSPHRASE: ${{ secrets.PASSPHRASE }}
```
This failed with 
And then updated it with the new GHA:
```
- name: Import GPG key
id: import_gpg
uses: …
```

fix: Change deprecated GPG build dependency

---

.github/workflows/goreleaser.yml
Makefile
README.md
docs/index.md

Bumping max version of `go-version` to allow `goreleaser` finish its job. 
Failed job: https://github.com/nobl9/terraform-provider-nobl9/runs/7634041747?check_suite_focus=true#step:7:28

Bump go-version for goreleaser

---

Makefile
README.md
docs/index.md
examples/provider/provider.tf
nobl9/provider.go
nobl9/provider_test.go
nobl9/resource_agent_test.go
nobl9/resource_alert_policy_test.go
nobl9/resource_alertmethod_test.go
nobl9/resource_project_test.go
nobl9/resource_role_binding_test.go
nobl9/resource_service_test.go
nobl9/resource_slo_test.go

Reusing the N9 client for all API calls caused using an invalid project
for some of the requests. Now clients are created per individual
project.
Resolves: PC-6512

 reuse n9 client per project

---

docs/resources/slo.md
examples/resources/nobl9_slo/resource.tf

There is no example how to use Ratio Metric (a.k.a. count metrics) in n9 via terraform provider. I added this example to the standard SLO page.
It will appear [here](https://registry.terraform.io/providers/nobl9/nobl9/latest/docs/resources/slo#example-usage)

Add Ratio Metric Example to docs

---

nobl9/resource_role_binding.go

Before this change we were able to apply two role bindings one for organization role and one for project role. Terraform query for role bindings by name. This condition caused to throw error by terraform. (WE apply resource and check if it was applied)
``` go 
func unmarshalRoleBinding(d *schema.ResourceData, objects []n9api.AnyJSONObj) diag.Diagnostics {
if len(objects) != 1 {
d.SetId("")
return nil
}
```
Apply of resource that is after returned as nil cause this error.
```
Error: Provider produced inconsistent result after apply
```
To fix this issue I'm checking if role is project role or organization role by looking in project_ref is set.

Fix inconsistent role bindings

---

go.mod
go.sum
nobl9/provider.go
nobl9/resource_agent.go
nobl9/resource_role_binding.go
nobl9/resource_slo.go

This PR introduces retry mechanism for resources that their may fail due nobl9 internal service problem with concurrent requests. Retrying this requests always solve this issue. It is done by using terraform sdk [resource.RetryContext](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts#:~:text=WithoutTimeout%20CRUD%20functions.-,Retry,-The%20retry%20helper) function. 
This functionality is implemented:
- slos, 
- role bindings,
- agents.
For operations:
- apply,
-  update,
- delete.
If it will be tested before releasing new nobl9-go it need to have that replace in go.mod and run `go mod tidy` 
```
replace github.com/nobl9/nobl9-go => github.com/nobl9/nobl9-go 3764bbec8a5200d51a497c0def3f8a17e1b2f272
```
Easiest way to test this is to apply …

Retry for concurrent issues

---

nobl9/resource_slo.go
nobl9/resource_slo_test.go

When `total` or `good` metric spec for `count_metric` was not provided it ended up with index out of range error. `total` and `good` should both be required in the schema, instead they were marked as optionl.
I tested it by running all the tests, here's how to do that: https://nobl9.atlassian.net/wiki/spaces/FOUNDATIONS/pages/2255486981/Configuring+environments+for+Terraform

Change metric_spec to required

---

Makefile
README.md
docs/resources/alert_method_email.md
examples/resources/nobl9_alert_method_email/resource.tf
nobl9/resource_alertmethod.go
nobl9/resource_alertmethod_test.go

The goal of this PR is to make email Subject and Body variables _Optional_ and _Deprecated_.
They are kept in the struct for backwards compatibility (to avoid breaking changes) but a Warning will appear whenever people have them in their config file. Example:
Apply scenario with subject and/or body in the structure
```
resource "nobl9_alert_method_email" "this" {
name         = "my-email-alert"
display_name = "My Email Alert"
project      = "My Project"
description = "teams"
to          = [ "testUser@nobl9.com" ]
cc          = [ "testUser@nobl9.com" ]
bcc         = [ "testUser@nobl9.com" ]
subject     = "Test email, please ignore"
body        = "This is just a test email"
}
```
You should see warning in the console (about deprecated)
Apply case without them in the structure
```
resource …
```

Make email subject and body optional

---

Makefile
README.md
docs/resources/alert_policy.md
nobl9/resource_alert_policy.go
nobl9/resource_alert_policy_test.go

Introduced new measurement `timeToBurnEntireBudget` for alerting available to be configured with sloctl. We want to allow users to configure new condition type with Terraform too.
- https://github.com/nobl9/nobl9-go/pull/78
Tested on dev-sapphire with `main.tf` and following this [steps](https://nobl9.atlassian.net/wiki/spaces/FOUNDATIONS/pages/2370797596/Terraform+releases):
```terraform
terraform {
required_providers {
nobl9 = {
source  = "nobl9.com/nobl9/nobl9"
version = "0.15.0"
}
}
}
provider "nobl9" {
organization     = "nobl9-dev"
project          = "default"
ingest_url       = "https://dev-sapphire.nobl9.dev/api"
okta_org_url     = "https://accounts.nobl9.dev"
okta_auth_server = "ausdh506kj9JJVw3g4x6"
client_id        = "<CLIENT_ID>"
client_secret    = "<CLIENT_SECRET>"
}
resource …
```

PC-9535: Add support for entire budget would be exhausted

---

nobl9/resource_alert_policy_test.go

Motivation
---
Failing tests on [CI](https://g.codefresh.io/build/64c25478f537ed315a417c41?step=test&tab=output&logs=terminal) :
Summary
---
Some time ago we decreased the limit of the alert policy conditions to 3. I had to create new alert policy just with new measurement.
Testing
---
https://g.codefresh.io/build/64c270e7f45bfa93129f5b30?step=test&tab=output&logs=terminal

PC-9535: Fix for failing ACC tests

---

nobl9/resource_alert_policy.go

A recent PR to nobl9-go (https://github.com/nobl9/nobl9-go/pull/89) changed the required operator for `time_to_burn_entire_budget` to `lte` (from `lt`). 
This PR reflects that change in the provider.

Change `time_to_burn_entire_budget` operator to lte

---

docs/resources/slo.md
nobl9/resource_agent_test.go
nobl9/resource_slo.go
nobl9/resource_slo_test.go

Add optional `account_id` field for cloudwatch metrics.

PC-10771 AWS cross-account observability support

---

nobl9/provider.go

With the turmoil over SDK changes in the past months, we've missed UserAgent from `sdk.Client` setup.
This PR brings it back.

fix: Set UserAgent

---

go.mod

Remove `toolchain` declaration which was added by mistake in https://github.com/nobl9/terraform-provider-nobl9/commit/5e7b359c4eee60bdf4d69f105d5c3148be951a10.

chore: Remove toolchain declaration

---

.github/workflows/release-candidate.yml
.github/workflows/release.yml

In order to mimic the release flow of sloctl we should be able to create release candidate which would not be pushed to Terraform registry but would still trigger acceptance tests.

chore: Add release candidate workflow

---

.github/workflows/release-candidate.yml
.github/workflows/release.yml

Turns out reusable workflow cannot be called from the step level but instead must be be called from job level.

chore: Fix release workflow

---

.github/workflows/acc-tests.yml
nobl9/provider.go

Set empty string instead of nil to "cheat" Terraform into thinking we did provide required variable (even though we didn't).

chore: Fix acceptance tests env variable names

---

.github/workflows/acc-tests.yml

When calling this reusable workflow from an external repository it is required to explicitly set the right repository and reference name in order to make sure the terraform-provider-nobl9 is checked out, instead of the calling repository.
Ref: https://github.com/actions/checkout.

chore: Adjust acceptance tests workflow

---

.github/workflows/release.yml
dev-docs/DEVELOPMENT.md
dev-docs/RELEASE.md

Moved some docs from Confluence, added standard DEVELOPMENT and RELEASE documents.
Both documents must be placed somewhere else then `docs`, as `docs` host the generate Terraform documentation.
Ref: https://github.com/nobl9/sloctl/pull/68

chore: Introduce SOC-2 compliant release workflow

---

dev-docs/DEVELOPMENT.md
nobl9/resource_agent_test.go
nobl9/resource_direct_test.go

Acceptance tests are failing.
Lightstep direct tests were using an invalid field name. This PR solves this issue.
I also updated development docs since the environment variables provided there didn't work.
https://github.com/nobl9/terraform-provider-nobl9/commit/2e199e5aaf3a502f9a0610aab1cc92d7a890d888

test: fix lightstep direct test

---

.github/workflows/acc-tests-dispatch.yml
dev-docs/DEVELOPMENT.md
nobl9/resource_alert_policy.go

ACC tests are failing because detecting changes in `lasts_for` (that was previously set to default 5m when not defined) and cooldown (that is new in Terraform) 
https://github.com/nobl9/n9/actions/runs/8169474253/job/22338158247
Repeat logic that is implemented in Ingest:
- When cooldown is not defined, default 5m cooldown is set - which is aligned with our API, no diff with existing alert policies should be detected.
- When none of `lasts_for` or `alerting_window` is configured, then we can assume that `lasts_for=0m`. However, we cannot use default '0m' for this field because API would return validation error when user wants to set `alerting_window`. 
- https://github.com/nobl9/terraform-provider-nobl9/pull/177
- https://github.com/nobl9/terraform-provider-nobl9/actions/runs/8179122240 …

fix: Default values for alert policy empty `cooldown` and `lasts_for` to be backward compatible

---

README.md

The previous logo was referencing the wrong asset.

chore: Update README.md logo

---

.goreleaser.yml

https://github.com/nobl9/sloctl/pull/103

chore: Fix goreleaser marking pre-releases as latest

---

Makefile
docs/resources/alert_policy.md
examples/resources/nobl9_alert_policy/resource.tf
nobl9/resource_alert_policy.go
nobl9/resource_alert_policy_test.go
nobl9/resource_slo_test.go

Allow user to define any valid mathematical operator for `burnedBudget` condition type maintaining backward compatibility (using default operator).
We want also to update examples for Terraform provider that includes new alerting conditions (time to burn budget / time to burn entire budget based on alerting window and configurable mathematical operator for burned budget).
When user provide no mathematical operator to avoid false differences use default operator for given measurement type. It requires changes provided in https://github.com/nobl9/nobl9-go/pull/377
Added more ACC tests for alert policy.
It looks like this example didn't work correctly. I fixed by changing the condition [here](https://github.com/nobl9/terraform-provider-nobl9/blob/15c27dacb13dc01d0b0cdc4c21147462e1fbc270/nobl9 …

PC-12653+PC-12085 feat: Allow to set mathematical operator for burnedBudget alerting condition

---

.github/workflows/acc-tests-dispatch.yml

`vars` scope cannot be used inside `default` value for dispatch inputs.

chore: Correct default project for acceptance tests dispatch workflow

---

Makefile
README.md
docs/resources/slo.md
nobl9/resource_slo.go
nobl9/resource_slo_composite.go

Adding a uniqueness requirement on composite 2.0 SLO blocks `composite`, `components` and `objectives` would make the composite 2.0 SLOs creation process more intuitive.
Added a uniqueness requirement on composite 2.0 SLO blocks `composite`, `components` and `objectives`.

chore: PC-13868 Fix composite 2.0 block uniqueness

---

.github/workflows/release.yml

v5 uses node 16, which is unsupported by GHA

chore: Update crazy-max/ghaction-import-gpg to v6

---

.github/renovate.json5

We want to manually and with care govern the dependency management of nobl9-go.

chore: Ignore nobl9-go in Renovate config

---

nobl9/resource_agent_test.go

Splunk Observability only works in the `alpha` release channel. These changes updates the acceptance test to the new behavior.

chore: fix Splunk Observability acceptance test [PC-14221]

---

README.md

We want to keep examples in readme up to date.
Bumped version referenced in readme examples to the next published verstion.

chore: Bump version number for release

---

Makefile
cspell.yaml

By default `go fmt` calls `gofmt -w -l`, with the recent golangci linter changes it seems it's not enough, and rightfully so.
It now requires the files to be formatted with `-s` flag which simplifies code, for instance removing unnecessary type literals in slice declarations. 
Example linter fail due to unsimplified code: https://github.com/nobl9/nobl9-go/actions/runs/11123928510/job/30908411560

chore: Update gofmt usage

---

nobl9/resource_slo_test.go

Removed "t.Parallel" setting from two tests that are negatively affected by it.

chore: Unparallel SLO and SLO Errors tests

---

docs/resources/alert_policy.md
nobl9/resource_alert_policy.go

Typo in measurement name in documentation. Instead of `burnRate` it's expected to see provide `averageBurnRate` measurement name.
Fixed docs `burnRate` => `averageBurnRate`.

fix: Typo in alerting measurement name in docs

---

nobl9/resource_slo.go

Setting `ForceNew` will now display a warning both in plan and during apply.
`service` property in `nobl9_slo` resource is now causing a new resource to be created in place of the existing one if it was changed. It will now follow the same rule as `project` or `name` properties. The lack of such validation was an oversight and does not modify any existing Nobl9 platform rules.

fix: Set ForceNew to true for service in SLO

---

Makefile
README.md
docs/index.md
docs/resources/slo.md
examples/provider/provider.tf
nobl9/resource_slo.go

Allow Nobl9 users to automatically launch historical data retrieval (Replay) when creating new SLOs using the Nobl9 Terraform Provider.
Introduces the ability to trigger a replay (historical data retrieval) for a newly created SLO by adding the `retrieve_historical_data_from` parameter. Appropriate messaging is provided to the user.
**Caveats:**
- The SLO is created regardless of the success of the Replay trigger.  
- Replay availability for the datasource used by the SLO is not validated.  
- All Replay errors are printed.
**Example**
`retrieve_historical_data_from  = "2024-11-14T13:00:00Z"`
This feature is most useful when aligned with the Playlist (Replay queues) feature; however, it is fully functional with current slot limitations.
Creating and updating multiple SLOs with datasources …

feat: Trigger replay on SLO creation

---

docs/resources/alert_method_email.md
nobl9/resource_alertmethod.go
nobl9/resource_alertmethod_test.go

Removed deprecated fields `Subject` and `Body` for Email alert method.
Fields were marked as deprecated in 2024 July ( https://github.com/nobl9/terraform-provider-nobl9/releases/tag/v0.14.0  ) and were ignored by API since then.
- Upcoming SDK version https://github.com/nobl9/nobl9-go/releases/tag/v0.91.0-rc3
- Passing [acceptance tests](https://github.com/nobl9/terraform-provider-nobl9/actions/runs/12137243789/job/33840060050) for alert methods ✅ 
- Passing `make test/unit` ✅ 
- Manual test ✅ 
```terraform
terraform {
required_providers {
nobl9 = {
source = "nobl9.com/nobl9/nobl9"
version = "0.32.2"
}
}
}
provider "nobl9" {
client_id = ""
client_secret = ""
okta_org_url     = ""
okta_auth_server = ""
}
resource "nobl9_project" "this" {
display_name = "Test N9 Terraform"
name         = …
```

chore: Remove deprecated 'Subject' and 'Body' support from Email alert method.

---

go.mod

I am manually bumping go version to the newest available to avoid issue with renovate failing to install `govulncheck` tool:
https://github.com/nobl9/terraform-provider-nobl9/actions/runs/12235599079/job/34127224087
The issue comes probably from `actions/setup-go` always configuring version of go coming from `go` directive. It seems that version declared in `toolchain` is also installed but there are a bunch of warning reported so I am assuming something is wrong with that step. `toolchain` directive is added and by Renovate. Bumping `go` directive is now disabled by default.  I don't know why exactly it stops working as setting different `toolchain` should be forward-compatible but here we are.
Bump go version to `1.23.4`
https://github.com/nobl9/terraform-provider-nobl9/pull/336 …

chore: Bump go version to 1.23.4

---

Makefile

With the recent changes and the introduction of Terraform Plugin Framework we needed to shift `Version` variable declaration away from `nobl9` package to `main`. It turns out `go build` expects the `main` package path to be just `main` instead of the module's name prefix.

fix: Correct version handling

---

nobl9/resource_slo.go

With introduction of [triggering replay on SLO creation](https://github.com/nobl9/terraform-provider-nobl9/pull/342) the code tried to lunch replay even if SLO creation failed and that caused a `panic`.
- Create SLO with a non-existent data source.

fix: Perform replay only if SLO is created successfully

---

docs/resources/slo.md
nobl9/resource_slo.go

This PR corrects formatting (missing spaces) in the description of the `value` field for the `nobl9_slo` resource.

chore: Update value description

---

docs/resources/alert_method_webhook.md
go.mod
go.sum
nobl9/resource_alertmethod.go
nobl9/resource_alertmethod_test.go

Webhook alert method does not support custom HTTP headers now.
- the headers in .tf are split into `headers` and `sensitive_headers` to allow settings secrets..
```
resource "nobl9_alert_method_webhook" "webhook" {
name            = "webhook"
project         = "default"
url             = "http://web.net"
template        = "SLO needs attention $slo_name"
headers         = {
"X-Custom-Header" = "custom value"
}
sensitive_headers = {
"Authorization" = "Bearer xyz"
}
}
```
Webhook alert method now supports custom HTTP headers.

feat: Add custom headers support for Webhook AlertMethod

---

docs/resources/alert_method_webhook.md
templates/resources/alert_method_webhook.md.tmpl

This PR updates a broken link to the main Nobl9 documentation for the Webhook alert method.

chore: Update broken link for webhook

---

docs/resources/alert_method_slack.md
examples/resources/nobl9_alert_method_slack/resource.tf
nobl9/resource_alert_policy_test.go
nobl9/resource_alertmethod_test.go

Fix failing Terraform Acceptance tests
* Updated invalid URLs for slack and opsgenie alert methods.
* https://github.com/nobl9/terraform-provider-nobl9/actions/runs/12808258859/job/35710591061

fix: PC-9592 Update opsgenie, slack URLs in tests

---

docs/resources/slo.md
nobl9/resource_slo.go
nobl9/resource_slo_test.go

Support for single query splunk ratio SLOs
Example:
```
objective {
display_name = "obj1"
name         = "tf-objective-1"
primary      = false
target       = 0.7
time_slice_target = 0
value        = 1
count_metrics {
incremental = true
good_total {
splunk {
query = "| mstats avg(\"spl.intr.resource_usage.IOWait.data.avg_cpu_pct\") as n9good WHERE index=\"_metrics\" span=15s | join type=left _time [ | mstats avg(\"spl.intr.resource_usage.IOWait.data.max_cpus_pct\") as n9total WHERE index=\"_metrics\" span=15s] | rename _time as n9time | fields n9time n9good n9total"
}
}
}
}
```
Support for single query splunk ratio SLOs

feat: Support for single query splunk ratio SLOs [PC-13052]

---

nobl9/resource_slo_test.go

The validation message in nobl9-sdk changed after we introduced a single query.

chore: fix message error in test that validates metrics.

---

Makefile
README.md
docs/index.md
examples/provider/provider.tf

This pull request includes a version update for the `nobl9` provider from `0.37.0` to `0.37.1` across multiple files. The changes ensure the documentation and example configurations are consistent with the new version that's planned to release.

chore: Bump version of TF provider

---

.github/workflows/acc-tests.yml
docs/index.md
internal/frameworkprovider/env_configurable_bool.go
internal/frameworkprovider/provider.go
internal/frameworkprovider/provider_model.go
internal/frameworkprovider/sdk_client.go
nobl9/provider.go

The sdk client couldn't use token between tests. Removing the sdk.ConfigOptionNoConfigFile() option regarding the dedicated environment variable, allowed to store token in config file and use it in further test requests.

chore: Allow to cache token during acceptance tests run

---

.github/workflows/acc-tests.yml
docs/index.md
internal/frameworkprovider/env_configurable_bool.go
internal/frameworkprovider/provider.go
internal/frameworkprovider/provider_model.go
internal/frameworkprovider/sdk_client.go
nobl9/provider.go

Describe what is the motivation behind the proposed changes.
If possible reference the current solution/state of affairs.
The previous version hasn't worked because of difference in env variable responsible to input Okta auth server url and identifier, where no TERRAFORM_NOBL9_ prefix is used. The old provider looks for  NOBL9_OKTA_URL and NOBL9_OKTA_AUTH not previously set NOBL9_OKTA_ORG_URL and NOBL9_OKTA_AUTH_SERVER.

chore: Allow to cache tokens

---

.goreleaser.yml

Recent changes to the Goreleaser started breaking our release process which involves creating pre-release versions. These releases are marked by us as pre-release and contain `-rc` suffix. Unfortunately Goreleaser started removing pre-release flag from them when publishing artifacts.
This PR fixes it.
https://github.com/nobl9/sloctl/pull/304

chore: Update goreleaser

---

nobl9/resource_slo.go

Currently this warning is ALWAYS displayed, it should only be shown if there's an objective without a name.
Terraform plan will no longer display a warning for setting objective names If all the objectives have names.

fix: Correct objective name warning

---

README.md
go.mod
go.sum
internal/frameworkprovider/provider_test.go
internal/frameworkprovider/slo_resource.go
internal/frameworkprovider/slo_resource_schema.go
internal/frameworkprovider/slo_resource_test.go

After the latest release it was not possible to set an empty list of alert policies in the SLO.
```
Error: Invalid Attribute Value
with module.alerting.nobl9_slo.slo_c2ab7e2e_15c3_4523_b831_517563d77a3e,
on ../services/alerting/main.tf line 2410, in resource "nobl9_slo" "slo_c2ab7e2e_15c3_4523_b831_517563d77a3e":
2410:   alert_policies   = []
Attribute alert_policies set must contain at least 1 elements, got: 0
```
- Removed the minElements = 1 validation
- Hacked SLOResource to compensate for case when nobl9 API does not return an empty list (because of omit empty)
- create SLO with empty alert policy
- create SLO with no alert policy
- create SLO with some alert policy
- detect drift if alert policies were changed from empty to filled
- detect drift if alert policies were changed from …

fix: Empty AlertPolicies list in SLO
